version: '3'

services:
  database:
    env_file:
      - database_service.env
    image: postgres:10.2-alpine
    restart: always
    ports:
      - "5432:5432"
  dropper:
    env_file:
      - dropper_service.env
    depends_on:
      - database
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 50051
    ports:
      - "50051:50051"
    command: "./wait_db_and_start.sh"
