version: '3'

services:
  dropper_database:
    env_file:
      - dropper_database.env
    image: postgres:10.2-alpine
    restart: always
    ports:
      - "5432:5432"
  dropper:
    env_file:
      - dropper.env
    depends_on:
      - dropper_database
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 50051
    ports:
      - "50051:50051"
    command: ["./wait_for_postgres.sh", "bin/dropper foreground"]
