# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payment.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "dropper.payment.Payer" do
    optional :name, :string, 1
    optional :email, :string, 2
  end
  add_message "dropper.payment.CreateRequest" do
    optional :payer, :message, 1, "dropper.payment.Payer"
    optional :method, :enum, 2, "dropper.payment.Method"
  end
  add_message "dropper.payment.CreateResponse" do
    optional :success, :bool, 1
    optional :id, :string, 2
    map :errors, :string, :string, 3
  end
  add_enum "dropper.payment.Method" do
    value :CC, 0
    value :TICKET, 1
    value :DEBT, 2
  end
end

module Dropper
  module Payment
    Payer = Google::Protobuf::DescriptorPool.generated_pool.lookup("dropper.payment.Payer").msgclass
    CreateRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("dropper.payment.CreateRequest").msgclass
    CreateResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("dropper.payment.CreateResponse").msgclass
    Method = Google::Protobuf::DescriptorPool.generated_pool.lookup("dropper.payment.Method").enummodule
  end
end
